// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.12.4
// source: zgs_grpc.proto

package zgs_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	ZgsGrpcService_Ping_FullMethodName                  = "/zgs_grpc.ZgsGrpcService/Ping"
	ZgsGrpcService_UploadSegmentsByTxSeq_FullMethodName = "/zgs_grpc.ZgsGrpcService/UploadSegmentsByTxSeq"
)

// ZgsGrpcServiceClient is the client API for ZgsGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// A trivial ping service
type ZgsGrpcServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	UploadSegmentsByTxSeq(ctx context.Context, in *UploadSegmentsByTxSeqRequest, opts ...grpc.CallOption) (*Empty, error)
}

type zgsGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewZgsGrpcServiceClient(cc grpc.ClientConnInterface) ZgsGrpcServiceClient {
	return &zgsGrpcServiceClient{cc}
}

func (c *zgsGrpcServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingReply)
	err := c.cc.Invoke(ctx, ZgsGrpcService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zgsGrpcServiceClient) UploadSegmentsByTxSeq(ctx context.Context, in *UploadSegmentsByTxSeqRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ZgsGrpcService_UploadSegmentsByTxSeq_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZgsGrpcServiceServer is the server API for ZgsGrpcService service.
// All implementations must embed UnimplementedZgsGrpcServiceServer
// for forward compatibility
//
// A trivial ping service
type ZgsGrpcServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingReply, error)
	UploadSegmentsByTxSeq(context.Context, *UploadSegmentsByTxSeqRequest) (*Empty, error)
	mustEmbedUnimplementedZgsGrpcServiceServer()
}

// UnimplementedZgsGrpcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedZgsGrpcServiceServer struct {
}

func (UnimplementedZgsGrpcServiceServer) Ping(context.Context, *PingRequest) (*PingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedZgsGrpcServiceServer) UploadSegmentsByTxSeq(context.Context, *UploadSegmentsByTxSeqRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadSegmentsByTxSeq not implemented")
}
func (UnimplementedZgsGrpcServiceServer) mustEmbedUnimplementedZgsGrpcServiceServer() {}

// UnsafeZgsGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZgsGrpcServiceServer will
// result in compilation errors.
type UnsafeZgsGrpcServiceServer interface {
	mustEmbedUnimplementedZgsGrpcServiceServer()
}

func RegisterZgsGrpcServiceServer(s grpc.ServiceRegistrar, srv ZgsGrpcServiceServer) {
	s.RegisterService(&ZgsGrpcService_ServiceDesc, srv)
}

func _ZgsGrpcService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZgsGrpcServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZgsGrpcService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZgsGrpcServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZgsGrpcService_UploadSegmentsByTxSeq_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadSegmentsByTxSeqRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZgsGrpcServiceServer).UploadSegmentsByTxSeq(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZgsGrpcService_UploadSegmentsByTxSeq_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZgsGrpcServiceServer).UploadSegmentsByTxSeq(ctx, req.(*UploadSegmentsByTxSeqRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ZgsGrpcService_ServiceDesc is the grpc.ServiceDesc for ZgsGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZgsGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zgs_grpc.ZgsGrpcService",
	HandlerType: (*ZgsGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ZgsGrpcService_Ping_Handler,
		},
		{
			MethodName: "UploadSegmentsByTxSeq",
			Handler:    _ZgsGrpcService_UploadSegmentsByTxSeq_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zgs_grpc.proto",
}
