// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: zgs_grpc.proto

package zgs_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zgs_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_zgs_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_zgs_grpc_proto_rawDescGZIP(), []int{0}
}

// / 32-byte hash root
type DataRoot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DataRoot) Reset() {
	*x = DataRoot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zgs_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataRoot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRoot) ProtoMessage() {}

func (x *DataRoot) ProtoReflect() protoreflect.Message {
	mi := &file_zgs_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRoot.ProtoReflect.Descriptor instead.
func (*DataRoot) Descriptor() ([]byte, []int) {
	return file_zgs_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *DataRoot) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// / A proof over a file-segment Merkle tree
type FileProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// / sequence of 32-byte hashes
	Lemma [][]byte `protobuf:"bytes,1,rep,name=lemma,proto3" json:"lemma,omitempty"`
	// / bit-paths (left=false, right=true) alongside the lemmas
	Path []bool `protobuf:"varint,2,rep,packed,name=path,proto3" json:"path,omitempty"`
}

func (x *FileProof) Reset() {
	*x = FileProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zgs_grpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileProof) ProtoMessage() {}

func (x *FileProof) ProtoReflect() protoreflect.Message {
	mi := &file_zgs_grpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileProof.ProtoReflect.Descriptor instead.
func (*FileProof) Descriptor() ([]byte, []int) {
	return file_zgs_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *FileProof) GetLemma() [][]byte {
	if x != nil {
		return x.Lemma
	}
	return nil
}

func (x *FileProof) GetPath() []bool {
	if x != nil {
		return x.Path
	}
	return nil
}

// / A file segment plus its Merkle proof
type SegmentWithProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Root     *DataRoot  `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`                          // file Merkle root
	Data     []byte     `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                          // raw segment bytes
	Index    uint64     `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`                       // segment index
	Proof    *FileProof `protobuf:"bytes,4,opt,name=proof,proto3" json:"proof,omitempty"`                        // Merkle proof of this leaf
	FileSize uint64     `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"` // total file length
}

func (x *SegmentWithProof) Reset() {
	*x = SegmentWithProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zgs_grpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentWithProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentWithProof) ProtoMessage() {}

func (x *SegmentWithProof) ProtoReflect() protoreflect.Message {
	mi := &file_zgs_grpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentWithProof.ProtoReflect.Descriptor instead.
func (*SegmentWithProof) Descriptor() ([]byte, []int) {
	return file_zgs_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *SegmentWithProof) GetRoot() *DataRoot {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *SegmentWithProof) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SegmentWithProof) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SegmentWithProof) GetProof() *FileProof {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *SegmentWithProof) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type UploadSegmentsByTxSeqRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Segments []*SegmentWithProof `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	TxSeq    uint64              `protobuf:"varint,2,opt,name=tx_seq,json=txSeq,proto3" json:"tx_seq,omitempty"`
}

func (x *UploadSegmentsByTxSeqRequest) Reset() {
	*x = UploadSegmentsByTxSeqRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zgs_grpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadSegmentsByTxSeqRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSegmentsByTxSeqRequest) ProtoMessage() {}

func (x *UploadSegmentsByTxSeqRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zgs_grpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSegmentsByTxSeqRequest.ProtoReflect.Descriptor instead.
func (*UploadSegmentsByTxSeqRequest) Descriptor() ([]byte, []int) {
	return file_zgs_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *UploadSegmentsByTxSeqRequest) GetSegments() []*SegmentWithProof {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *UploadSegmentsByTxSeqRequest) GetTxSeq() uint64 {
	if x != nil {
		return x.TxSeq
	}
	return 0
}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zgs_grpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zgs_grpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_zgs_grpc_proto_rawDescGZIP(), []int{5}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zgs_grpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_zgs_grpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_zgs_grpc_proto_rawDescGZIP(), []int{6}
}

func (x *PingReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_zgs_grpc_proto protoreflect.FileDescriptor

var file_zgs_grpc_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x7a, 0x67, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x7a, 0x67, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x20, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x52, 0x6f, 0x6f, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x35, 0x0a, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x72, 0x6f,
	0x6f, 0x66, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x6d, 0x6d, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0c, 0x52, 0x05, 0x6c, 0x65, 0x6d, 0x6d, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x08, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0xac, 0x01, 0x0a,
	0x10, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x57, 0x69, 0x74, 0x68, 0x50, 0x72, 0x6f, 0x6f,
	0x66, 0x12, 0x26, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x7a, 0x67, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x6f, 0x6f, 0x74, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x29, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x7a, 0x67, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x1b,
	0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x6d, 0x0a, 0x1c, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x79, 0x54,
	0x78, 0x53, 0x65, 0x71, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x08, 0x73,
	0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x7a, 0x67, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x57, 0x69, 0x74, 0x68, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x08, 0x73, 0x65, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x78, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x78, 0x53, 0x65, 0x71, 0x22, 0x27, 0x0a, 0x0b, 0x50, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x25, 0x0a, 0x09, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x96, 0x01, 0x0a, 0x0e, 0x5a,
	0x67, 0x73, 0x47, 0x72, 0x70, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a,
	0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x15, 0x2e, 0x7a, 0x67, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x7a,
	0x67, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x50, 0x0a, 0x15, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x65, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x42, 0x79, 0x54, 0x78, 0x53, 0x65, 0x71, 0x12, 0x26, 0x2e, 0x7a, 0x67, 0x73,
	0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x65, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x42, 0x79, 0x54, 0x78, 0x53, 0x65, 0x71, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x7a, 0x67, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x30, 0x67, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x30, 0x67, 0x2d, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x2d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x7a, 0x67, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_zgs_grpc_proto_rawDescOnce sync.Once
	file_zgs_grpc_proto_rawDescData = file_zgs_grpc_proto_rawDesc
)

func file_zgs_grpc_proto_rawDescGZIP() []byte {
	file_zgs_grpc_proto_rawDescOnce.Do(func() {
		file_zgs_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_zgs_grpc_proto_rawDescData)
	})
	return file_zgs_grpc_proto_rawDescData
}

var file_zgs_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_zgs_grpc_proto_goTypes = []any{
	(*Empty)(nil),                        // 0: zgs_grpc.Empty
	(*DataRoot)(nil),                     // 1: zgs_grpc.DataRoot
	(*FileProof)(nil),                    // 2: zgs_grpc.FileProof
	(*SegmentWithProof)(nil),             // 3: zgs_grpc.SegmentWithProof
	(*UploadSegmentsByTxSeqRequest)(nil), // 4: zgs_grpc.UploadSegmentsByTxSeqRequest
	(*PingRequest)(nil),                  // 5: zgs_grpc.PingRequest
	(*PingReply)(nil),                    // 6: zgs_grpc.PingReply
}
var file_zgs_grpc_proto_depIdxs = []int32{
	1, // 0: zgs_grpc.SegmentWithProof.root:type_name -> zgs_grpc.DataRoot
	2, // 1: zgs_grpc.SegmentWithProof.proof:type_name -> zgs_grpc.FileProof
	3, // 2: zgs_grpc.UploadSegmentsByTxSeqRequest.segments:type_name -> zgs_grpc.SegmentWithProof
	5, // 3: zgs_grpc.ZgsGrpcService.Ping:input_type -> zgs_grpc.PingRequest
	4, // 4: zgs_grpc.ZgsGrpcService.UploadSegmentsByTxSeq:input_type -> zgs_grpc.UploadSegmentsByTxSeqRequest
	6, // 5: zgs_grpc.ZgsGrpcService.Ping:output_type -> zgs_grpc.PingReply
	0, // 6: zgs_grpc.ZgsGrpcService.UploadSegmentsByTxSeq:output_type -> zgs_grpc.Empty
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_zgs_grpc_proto_init() }
func file_zgs_grpc_proto_init() {
	if File_zgs_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_zgs_grpc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zgs_grpc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*DataRoot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zgs_grpc_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*FileProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zgs_grpc_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SegmentWithProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zgs_grpc_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*UploadSegmentsByTxSeqRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zgs_grpc_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zgs_grpc_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*PingReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zgs_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zgs_grpc_proto_goTypes,
		DependencyIndexes: file_zgs_grpc_proto_depIdxs,
		MessageInfos:      file_zgs_grpc_proto_msgTypes,
	}.Build()
	File_zgs_grpc_proto = out.File
	file_zgs_grpc_proto_rawDesc = nil
	file_zgs_grpc_proto_goTypes = nil
	file_zgs_grpc_proto_depIdxs = nil
}
