package node

import (
	"context"
	"crypto/ecdsa"
	"encoding/hex"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const testChainID int64 = 16601 // 0G testnet

// Cross-language canary vector — generated by 0g-hot-storage-router's
// test/eip712_vector.py and asserted in eip712_test.go on the router side.
// If this vector ever fails here, the SDK's EIP-712 domain or type set has
// drifted from the router/frontend and every user signature will silently
// fail to recover. Regenerate via that python script if intentional.
const (
	vectorChainID           int64  = 16601
	vectorUser                     = "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
	vectorPrivateKey               = "0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a"
	vectorNonce             uint64 = 42
	vectorExpectedHash             = "0xc799ba2aa82383a722c14135692f44006310e82e09c5e281cb74bbff720b4c53"
	vectorExpectedSignature        = "0xa1f2149e67f239a2fc223ddb345ca79d93d04fd8ab222bef8027af351208850106433afa7078dc68b4c9733272211df7a2e9c6a7bfdc55d53815acbe1c57e1351c"
	vectorExpectedSigner           = "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
)

var vectorFileHashes = []string{
	"0x1111111111111111111111111111111111111111111111111111111111111111",
	"0x2222222222222222222222222222222222222222222222222222222222222222",
}

func generateTestKey(t *testing.T) *ecdsa.PrivateKey {
	t.Helper()
	key, err := crypto.GenerateKey()
	require.NoError(t, err)
	return key
}

func mustParseKey(t *testing.T, hexKey string) *ecdsa.PrivateKey {
	t.Helper()
	key, err := crypto.HexToECDSA(strings.TrimPrefix(hexKey, "0x"))
	require.NoError(t, err)
	return key
}

func recoverFromHash(t *testing.T, hash common.Hash, sig []byte) common.Address {
	t.Helper()
	normalized := make([]byte, 65)
	copy(normalized, sig)
	if normalized[64] >= 27 {
		normalized[64] -= 27
	}
	pubKey, err := crypto.Ecrecover(hash.Bytes(), normalized)
	require.NoError(t, err)
	return common.BytesToAddress(crypto.Keccak256(pubKey[1:])[12:])
}

func TestHashHotDownloadAuth_MatchesPythonVector(t *testing.T) {
	user := common.HexToAddress(vectorUser)
	hashes := make([]common.Hash, len(vectorFileHashes))
	for i, h := range vectorFileHashes {
		hashes[i] = common.HexToHash(h)
	}

	got, err := hashHotDownloadAuth(user, hashes, vectorNonce, vectorChainID)
	require.NoError(t, err)
	assert.Equal(t, common.HexToHash(vectorExpectedHash), got,
		"EIP-712 hash drifted from router/frontend — regenerate vector if intentional")
}

func TestSignDownloadRequest_RecoversToSigner(t *testing.T) {
	key := mustParseKey(t, vectorPrivateKey)
	user := crypto.PubkeyToAddress(key.PublicKey)
	hashes := make([]common.Hash, len(vectorFileHashes))
	for i, h := range vectorFileHashes {
		hashes[i] = common.HexToHash(h)
	}

	sig, err := signDownloadRequest(key, user, hashes, vectorNonce, vectorChainID)
	require.NoError(t, err)
	require.Len(t, sig, 65)

	hash, err := hashHotDownloadAuth(user, hashes, vectorNonce, vectorChainID)
	require.NoError(t, err)
	assert.Equal(t, user, recoverFromHash(t, hash, sig))
}

func TestSignDownloadRequest_VectorSignatureRecovers(t *testing.T) {
	user := common.HexToAddress(vectorUser)
	hashes := make([]common.Hash, len(vectorFileHashes))
	for i, h := range vectorFileHashes {
		hashes[i] = common.HexToHash(h)
	}

	hash, err := hashHotDownloadAuth(user, hashes, vectorNonce, vectorChainID)
	require.NoError(t, err)

	sigBytes, err := hex.DecodeString(strings.TrimPrefix(vectorExpectedSignature, "0x"))
	require.NoError(t, err)

	assert.Equal(t, common.HexToAddress(vectorExpectedSigner), recoverFromHash(t, hash, sigBytes))
}

func TestSignDownloadRequest_DifferentChainIDProducesDifferentSig(t *testing.T) {
	key := generateTestKey(t)
	user := crypto.PubkeyToAddress(key.PublicKey)
	fileHash := common.HexToHash("0xaaaa")

	sig1, err := signDownloadRequest(key, user, []common.Hash{fileHash}, 1, testChainID)
	require.NoError(t, err)
	sig2, err := signDownloadRequest(key, user, []common.Hash{fileHash}, 1, testChainID+1)
	require.NoError(t, err)
	assert.NotEqual(t, sig1, sig2, "chainId is part of the EIP-712 domain — sigs must differ")
}

func TestSignDownloadRequest_DifferentNonces(t *testing.T) {
	key := generateTestKey(t)
	user := crypto.PubkeyToAddress(key.PublicKey)
	fileHash := common.HexToHash("0xaaaa")

	sig1, err := signDownloadRequest(key, user, []common.Hash{fileHash}, 1, testChainID)
	require.NoError(t, err)
	sig2, err := signDownloadRequest(key, user, []common.Hash{fileHash}, 2, testChainID)
	require.NoError(t, err)
	assert.NotEqual(t, sig1, sig2)
}

func TestSignDownloadRequest_DifferentKeys(t *testing.T) {
	key1 := generateTestKey(t)
	key2 := generateTestKey(t)
	fileHash := common.HexToHash("0xbbbb")

	sig1, err := signDownloadRequest(key1, crypto.PubkeyToAddress(key1.PublicKey), []common.Hash{fileHash}, 100, testChainID)
	require.NoError(t, err)
	sig2, err := signDownloadRequest(key2, crypto.PubkeyToAddress(key2.PublicKey), []common.Hash{fileHash}, 100, testChainID)
	require.NoError(t, err)
	assert.NotEqual(t, sig1, sig2)
}

func TestGetDownloadAuth_Success(t *testing.T) {
	key := generateTestKey(t)
	user := crypto.PubkeyToAddress(key.PublicKey)

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		assert.Equal(t, http.MethodPost, r.Method)
		assert.Equal(t, "/download", r.URL.Path)
		assert.Equal(t, "application/json", r.Header.Get("Content-Type"))

		var req HotRouterDownloadRequest
		err := json.NewDecoder(r.Body).Decode(&req)
		require.NoError(t, err)

		assert.Equal(t, user.Hex(), req.User)
		assert.Len(t, req.FileHashes, 1)
		assert.NotEmpty(t, req.Signature)
		assert.NotZero(t, req.Nonce)

		// Verify the user's EIP-712 signature recovers to the user address.
		sigBytes, err := hex.DecodeString(strings.TrimPrefix(req.Signature, "0x"))
		require.NoError(t, err)
		require.Len(t, sigBytes, 65)

		fileHash := common.HexToHash(req.FileHashes[0])
		hash, err := hashHotDownloadAuth(user, []common.Hash{fileHash}, req.Nonce, testChainID)
		require.NoError(t, err)
		assert.Equal(t, user, recoverFromHash(t, hash, sigBytes))

		resp := HotRouterDownloadResponse{
			NodeURL:    "http://hot-node:6789",
			Provider:   "0x1111111111111111111111111111111111111111",
			FileHashes: req.FileHashes,
			MaxFee:     "1000000",
			Nonce:      12345,
			Signature:  "0xabcdef",
		}

		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}))
	defer server.Close()

	client := NewHotRouterClient(server.URL, testChainID)
	root := "0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"

	resp, err := client.GetDownloadAuth(context.Background(), key, []string{root})
	require.NoError(t, err)
	assert.Equal(t, "http://hot-node:6789", resp.NodeURL)
	assert.Equal(t, "0x1111111111111111111111111111111111111111", resp.Provider)
	assert.Equal(t, "1000000", resp.MaxFee)
	assert.Equal(t, uint64(12345), resp.Nonce)
	assert.Equal(t, "0xabcdef", resp.Signature)
	assert.Equal(t, []string{common.HexToHash(root).Hex()}, resp.FileHashes)
}

func TestGetDownloadAuth_MultipleRoots(t *testing.T) {
	key := generateTestKey(t)

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		var req HotRouterDownloadRequest
		json.NewDecoder(r.Body).Decode(&req)
		assert.Len(t, req.FileHashes, 3)

		resp := HotRouterDownloadResponse{
			NodeURL:    "http://hot-node:6789",
			Provider:   "0x1111",
			FileHashes: req.FileHashes,
			MaxFee:     "3000000",
			Nonce:      1,
			Signature:  "0xsig",
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}))
	defer server.Close()

	client := NewHotRouterClient(server.URL, testChainID)
	roots := []string{"0xaaaa", "0xbbbb", "0xcccc"}

	resp, err := client.GetDownloadAuth(context.Background(), key, roots)
	require.NoError(t, err)
	assert.Len(t, resp.FileHashes, 3)
}

func TestGetDownloadAuth_CacheMiss_404(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		http.Error(w, "file not cached", http.StatusNotFound)
	}))
	defer server.Close()

	key := generateTestKey(t)
	client := NewHotRouterClient(server.URL, testChainID)
	resp, err := client.GetDownloadAuth(context.Background(), key, []string{"0xaaaa"})
	require.NoError(t, err)
	assert.Nil(t, resp)
}

func TestGetDownloadAuth_RouterError(t *testing.T) {
	tests := []struct {
		name       string
		statusCode int
		body       string
	}{
		{"insufficient balance", http.StatusPaymentRequired, "insufficient balance"},
		{"unauthorized", http.StatusUnauthorized, "signature does not match user"},
		{"server error", http.StatusInternalServerError, "internal error"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				http.Error(w, tt.body, tt.statusCode)
			}))
			defer server.Close()

			key := generateTestKey(t)
			client := NewHotRouterClient(server.URL, testChainID)
			_, err := client.GetDownloadAuth(context.Background(), key, []string{"0xaaaa"})
			require.Error(t, err)
			assert.Contains(t, err.Error(), tt.body)
		})
	}
}

func TestGetBalance_Success(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		assert.Equal(t, http.MethodGet, r.Method)
		assert.Equal(t, "/balance", r.URL.Path)
		assert.NotEmpty(t, r.URL.Query().Get("user"))

		resp := HotRouterBalanceResponse{
			Balance:       "1000000000000000000",
			LocalReserved: "50000",
			Available:     "999999999999950000",
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}))
	defer server.Close()

	client := NewHotRouterClient(server.URL, testChainID)
	user := common.HexToAddress("0x1234567890abcdef1234567890abcdef12345678")

	resp, err := client.GetBalance(context.Background(), user)
	require.NoError(t, err)
	assert.Equal(t, "1000000000000000000", resp.Balance)
	assert.Equal(t, "50000", resp.LocalReserved)
	assert.Equal(t, "999999999999950000", resp.Available)
}

func TestGetBalance_NotFound(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		http.Error(w, "account not found", http.StatusNotFound)
	}))
	defer server.Close()

	client := NewHotRouterClient(server.URL, testChainID)
	_, err := client.GetBalance(context.Background(), common.HexToAddress("0x1234"))
	require.Error(t, err)
	assert.Contains(t, err.Error(), "account not found")
}

func TestGetService_Success(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		assert.Equal(t, http.MethodGet, r.Method)
		assert.Equal(t, "/service", r.URL.Path)
		assert.NotEmpty(t, r.URL.Query().Get("provider"))

		resp := HotRouterServiceResponse{
			PricePerByte: "1000",
			URL:          "http://node:6789",
			Active:       true,
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}))
	defer server.Close()

	client := NewHotRouterClient(server.URL, testChainID)
	provider := common.HexToAddress("0x1111111111111111111111111111111111111111")

	resp, err := client.GetService(context.Background(), provider)
	require.NoError(t, err)
	assert.Equal(t, "1000", resp.PricePerByte)
	assert.Equal(t, "http://node:6789", resp.URL)
	assert.True(t, resp.Active)
}

func TestGetService_NotFound(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		http.Error(w, "service not found", http.StatusNotFound)
	}))
	defer server.Close()

	client := NewHotRouterClient(server.URL, testChainID)
	_, err := client.GetService(context.Background(), common.HexToAddress("0x1234"))
	require.Error(t, err)
	assert.Contains(t, err.Error(), "service not found")
}

func TestGetDownloadAuth_ContextCanceled(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		<-r.Context().Done()
	}))
	defer server.Close()

	key := generateTestKey(t)
	client := NewHotRouterClient(server.URL, testChainID)

	ctx, cancel := context.WithCancel(context.Background())
	cancel()

	_, err := client.GetDownloadAuth(ctx, key, []string{"0xaaaa"})
	require.Error(t, err)
}

func TestGetDownloadAuth_InvalidJSON(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.Write([]byte("not valid json"))
	}))
	defer server.Close()

	key := generateTestKey(t)
	client := NewHotRouterClient(server.URL, testChainID)

	_, err := client.GetDownloadAuth(context.Background(), key, []string{"0xaaaa"})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "failed to decode router response")
}
